name: Build and Unit Tests

on:
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build-and-unittest:
    name:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Checkout submodules
      run: |
        git config --global url."https://github.com/".insteadOf "git@github.com:"
        auth_header="$(git config --local --get http.https://github.com/.extraheader)"
        git submodule sync --recursive
        git -c "http.extraheader=$auth_header" -c protocol.version=2 submodule update --init --force --recursive --depth=1

    - name: Install dependencies
      if: runner.os == 'Linux'
      run: |
        sudo add-apt-repository -n -y ppa:jonathonf/gcc-9.2
        sudo add-apt-repository -n -y ppa:mhier/libboost-latest
        sudo apt-get update
        sudo apt-get install -y gcc-9 g++-9 libopenmpi-dev scons libboost1.70-dev
        sudo update-alternatives --install /usr/bin/gcc gcc /usr/bin/gcc-9 60 --slave /usr/bin/g++ g++ /usr/bin/g++-9
        mpic++ --version

    - name: Install googletest
      if: runner.os == 'Linux'
      run: |
        sudo apt-get install -y libgtest-dev
        cd /usr/src/googletest
        sudo cmake .
        sudo make && sudo make install
        cd -

    - name: Build
      run: |
        scons

    - name: Unit tests
      run: |
        cd test
        ./testcsl
